[dr]
type: drive
scope: drive
token: {"access_token":"ya29.a0Aa7MYiqFwu9CzVErGzws37fxnFxmHlh17z4ArjSEZ5xRLIJIthC8dn1-oav9F2yHvonBzcR4P7zTU6gTBWTN5pwCxhmSmyYbAZpjUc__1YEYeYVQlKsLYj0deZcu-kv2hwjwWrNUtBIbhLahYOHYGI-lUv-yumZtr2hef9Uop9_aVuVANFR82qV6dDLnuA55nY0kdfoaCgYKAb4SARESFQHGX2Mix-OTqCjEAuR_OYBMecdVhw0206","token_type":"Bearer","refresh_token":"1//0g_LhZopFfWTFCgYIARAAGBASNwF-L9Ir0NW9IAlScHOzfk6k5r598-0x4faIXK49BT1EOZla75EIhVzyiZVJ7nvO1qG62Rxkeko","expiry":"2026-04-06T09:04:45.071336652Z","expires_in":3599}
